### ISSUE TITLE
Python mode fails to run

### ISSUE THREAD

**Issue by luanshixia** [jdf/Processing.py-Bugs#135]
I was using `Processing 2.2.1` Windows x64. Run any code in python mode, there is nothing but error message.

![image](https://cloud.githubusercontent.com/assets/4253867/9538735/8968b906-4d15-11e5-8667-b560617aa0be.jpg)

**Comment by valashko** [comment]
I am observing the same issue on Windows 7 32 bit

**Comment by yzaki** [comment]
I am also having the same issue. It does not seem to be a problem of processing but rather a problem of the python mode. Because if I write in Java it works.

Anyone figured out what the issue might be?

**Comment by jdf** [comment]
All development is currently happening in Python Mode for Processing 3; it's unlikely I'll be able to find and fix this bug.

**Comment by yzaki** [comment]
I might have posted in the wrong place but I am using processing 3.

Regards,
Yasir

**Comment by valashko** [comment]
@jdf, I believe this bug depends on the name of directory Processing is run from. I feel like specific symbols (spaces or non-ascii) may have an impact.

**Comment by jdf** [comment]
Thanks for the hint, @valashko! If someone can give me a way to reproduce this, I'd be grateful.

**Comment by valashko** [comment]
I'll give you more updates on the findings once I have my hypothesis tested. The thing everyone who is reporting the issue has in common is using a non-English language: myself and couple of my students, yzaki, luanshixia. This is the reason I suggested that language differences may be involved.

**Comment by yzaki** [comment]
I definitely agree. I have about 4 students who are having the same issue.
All of them are using a non English windows version. I think the python
mode is not working at all. I simply tried to do a variable assignment such
as x=5 and it did not work.

**Comment by yzaki** [comment]
Another bug that I discovered today is that the path outside the setup( ) and the draw () functions is not the same path within these functions. So if we would import os and then try to get the path by doing os.getcwd( ), for some machines (specially windows) the os.getcwd( ) will give you a path to a temporary location on your hard disk. 
However once you do the same inside the setup ( ) function then it will get the correct path where your sketch is and this also makes the path outside also points to the sketch folder. I think this is a bug.

The reason why we are doing this is if we try to load an image from a within the __init__ () method of a class and we instantiated the object outside the setup ( ) function, then we will need the full path to load the image. And getting the path sometimes creates issues because of what I explained earlier.

**Comment by valashko** [comment]
@jdf, the issue occurs if a user's home directory (where preferences.txt is located) is written in non-ascii characters. For example, if two users ("Temp" and "Светлана") on a single PC try to run a python sketch in processing, "Temp" succeeds and "Светлана" fails. I have observed the issue for Windows 7 32-bit both with Processing 2 and 3. To reproduce the issue simply create a new user called "Светлана", log in, and run any python sketch with Processing 3.0.1.

**Comment by jdf** [comment]
So this morning I bought a Windows laptop, just to address this issue.

I created a username, "Björn Feinberg", and installed Procesing 3.0.1. I'm not able to even run a clean install of processing, let alone install Python mode. When I double-click on the processing app in the Björn profile, I get "An error occurred during startup," with a huge stack trace in a dialog. Does that not happen for everyone else here?

**Comment by jdf** [comment]
Ah, some of you are talking about Processing 2, and I'm trying Processing 3. Has anyone else with non-ASCII characters in the username been able to even run Processing 3?

**Comment by jdf** [comment]
I have a pull request in that may fix this bug. It's a straightforward enough request; I hope they'll accept it soon. The bug is in Processing itself, and not in Python mode, as far as I can tell, and I therefore don't have the power to apply the fix myself.

https://github.com/processing/processing/pull/4204

**Comment by jdf** [comment]
My pull request was accepted. Could you please upgrade to the latest Processing, and reopen here if the bug is not fixed?
