### ISSUE TITLE
pythonmode doesn't install processing 3.3.6

### ISSUE THREAD

**Issue by rofoto** [jdf/Processing.py-Bugs#215]
Hi,

 I've recently decided to get back to processing and after updating to the latest version (3.3.6) pythonmode does not install, and constantly reports timeouts even though the package downloads. Ive tested on macosx 10.12.6, ubuntu 17.10 both the prebuilt package and manually built git repos on fresh installs of both OS's, on and off VPN ( to test if it actually is a network issue , i live in china ). 

Any help would be great.
Thanks

**Comment by rofoto** [comment]
Just tested on win10x64 and it installs on that platform.

**Comment by jdf** [comment]
@benfry FYI

As a workaround, you can always just download http://py.processing.org/3/PythonMode.zip and unzip it in the "modes" directory of your Processing data directory.

**Comment by benfry** [comment]
@jdf What would you like me to do?

**Comment by jdf** [comment]
Oh, truly just FYI, in case any other mode installer bugs are happening that I don't know about.

**Comment by rofoto** [comment]
Downloading and manually installing works, Thank you very much.

**Comment by benfry** [comment]
Is this broken for everyone?

**Comment by jdf** [comment]
@benfry I don't think it's broken for everyone, on all platforms. But between this report, and #167, we at least have evidence that it's flakey. Maybe I'll spend an evening looking at the contributions manager download code, and at least add some detailed logging to it so that future troubles can be better understood.

**Comment by benfry** [comment]
Hm, I don't think it's quite *that* broken… I was just able to install it just fine. 

My best guess is that we're hitting a problem when it's the current Mode, and one tries to update it, and files are still in use by the JVM. There's code to handle that (since this is an obvious/common case), but I suspect it's especially broken on Windows, which is especially clingy with file handles. 

The question for me would be:
* Is it updates or installation that is broken?
* And on which platforms?
* If you've not used Python Mode (i.e. it's not the default Mode, it's not the front window) in a session, is there still a problem when updating?

**Comment by jdf** [comment]
@rofoto Was this an initial install of Python Mode, or were you updating an existing installation?

**Comment by jdf** [comment]
@benfry Is there an API for Mode implementors that means "you're about to be updated; please close any open files and helper processes"? I ask because Python Mode does run multiple processes, which would need to be let go of.

**Comment by benfry** [comment]
@jdf Heh, nope. But that would certainly explain what's going on…

**Comment by rofoto** [comment]
@jdf every install attempt was done on both fresh and previous install/upgrades

**Comment by rofoto** [comment]
@jdf  also worth noting , I just tried to install the opencv library and have the same issue.

**Comment by rofoto** [comment]
This is what the library list looks like after library install reports failure. I tried twice so I suspect that the failure causes a new file to be made causing further errors 

![screen shot 2018-02-26 at 9 47 27 pm](https://user-images.githubusercontent.com/13305754/36671380-c42f3ab6-1b3e-11e8-9a5e-0f971df13281.png)

**Comment by jdf** [comment]
@rofoto If this also happens when installing a library having nothing to do with Python Mode, then the bug is (most likely) in Processing.  I'm closing this, and opening https://github.com/processing/processing/issues/5424.
