### ISSUE TITLE
python print() function bug

### ISSUE THREAD

**Issue by Enrique-ZA** [jdf/Processing.py-Bugs#283]
```
myname, mysurname = "John", "Smith"
print ("I am ", myname, mysurname)
```

`Output: ('I am ',  'John', 'Smith')
`

The correct output is:

`I am John Smith`

The above code is the same as using:

```
myname, mysurname = "John", "Smith"
print ("I am " + myname + " " + mysurname)
```

`Output:  I am John Smith`

This is also the same as:

```
myname, mysurname = "John", "Smith"
print ("I am " + str(myname) + " " + str(mysurname))
```

`Output:  I am John Smith`

**Comment by villares** [comment]
Hi @Enrique-Za!

This is not a bug because in Python 2 `print` is not a function, and Processing Python Mode is based on Jython (Python 2), so you are using the *print statement* followed by a tuple!

Check https://docs.python.org/3/whatsnew/3.0.html to have a better picture. Then you can have the Python 3 behaviour using this first thing in yout sketch:
```python
from __future__ import print_function

```

**Comment by Enrique-ZA** [comment]
Hi @villares, sorry, my mind is so used to python3, that I didn't even stop to think it might be python2 based. Thanks for clearing that up!
