### ISSUE TITLE
color() reference page

### ISSUE THREAD

**Issue by metacortexplus** [jdf/Processing.py-Bugs#296]
![py_bug](https://user-images.githubusercontent.com/21023720/82057834-9b3a3780-96cc-11ea-8e23-b7544dbf69f3.JPG)
Should be like `c = "#006699"`?

**Comment by villares** [comment]
Good catch, @Meta-Cortex!
This is not right in Python mode. I'll try to make a PR.

**Comment by metacortexplus** [comment]
Hello. The issue is still present on the site. Just wonder -- is there anyone who maintain docs site ? :)

**Comment by FeXd** [comment]
There are a lot of merges still waiting to be deployed to the site. 

@jdf Is the deployment supposed to be happenign automatically, through Travis, or is it manual? As per all of the webpage last deploy was: `Updated on Fri Aug 16 21:51:57 2019`

**Comment by villares** [comment]
@FeXd yeah, I think that something might be broken :cry: 

https://github.com/jdf/Processing.py-Bugs/issues/284

**Comment by jdf** [comment]
Hi, folks.

Deployment is very much not automatic. Unfortunately, I am unable to run the process that builds the site. I cannot find any combination of python version and the various versions of python dependencies required to build the site. If anyone else can do so, perhaps we can figure out a safe way to deploy.

**Comment by villares** [comment]
@jdf thank you so much for the immense work, so many things on your plate and then this arcane site pipeline, it must be a pain.

I think someone, at some point, mentioned they could build/generate it, it may have been @jeremydouglass, I'm not sure.

I'd chisel HTML in stone if it would help.

**Comment by FeXd** [comment]
Yes, thank you @jdf! 🙏  It's so great that you've been able to keep this going!

I was able to build the site back in January: https://github.com/jdf/processing-py-site/issues/142#issuecomment-575161909

I might be able to try building again and finding some way to automate. But based on my current availability, this might not be until December. 😢

**Comment by jeremydouglass** [comment]
@jdf -- after a little investigation:

right now, according to the site .travis.yml, Travis is building the site on their Trusty (Ubunutu 14) image.

That image [uses Python 2.7.13](https://docs.travis-ci.com/user/reference/trusty/#python-images) by default. It is also set up to use Java version "1.8.0_151" -- it should maybe be 8u202, but that doesn't seem to be causing any problems.

According to the last (and successful) [Travis build log](https://travis-ci.org/github/jdf/processing-py-site/builds/727386933), and it is installing dependencies from `requirements.txt` -- which contains no version numbers (oops), so it is installing the latest Jinja2 and lxml that work on Python 2.7.

Some of the options for reliable site builds:

-  option 1. local setup: configure your local machine to run the build with a 2.7 virtualenv, the requirements Jinja2 and lxml installed, and JAVA_HOME pointing to your local 8u151 or 8u202.

- option 2. create a Dockerfile that contains the above requirements and build from that, e.g. on top of an [existing Trusty+Java 8 image [1](https://hub.docker.com/r/erikadp/ubuntu-trusty-java8/dockerfile) [2](https://hub.docker.com/r/smurfsky101/docker-ubuntu-14-04-java8). We could then check the Dockerfile into the site repo.

- option 3. run travis locally, e.g. -- then you will have the exact same environment and get the site build artifacts just as they are being created on Travis. This looks fairly involved. https://stackoverflow.com/questions/21053657/how-to-run-travis-ci-locally/49019950#49019950

- option 4. add a `deploy` section to .travis.yml file, so that any tagged commit will automatically deploy its build files to somewhere -- for example, to the github releases section -- they can be downloaded and FTP'd to your source from there. Setting up requires an authorization token. It *may* also require that the build script zip up the site (so that the zip can be uploaded to releases as an attached file). For having the .travis.yml deploy selected files to github when a tagged commit passes, see:

    -  https://docs.travis-ci.com/user/deployment/releases/#uploading-multiple-files

**update** -- just realized that I actually built a Docker solution for myself back in August 2019. I'll look at adding the setup/config to the site files with instructions.

**Comment by jeremydouglass** [comment]
For now I've gone ahead and rebuilt the site locally and uploaded the site "generated" build to releases, here:

https://github.com/jdf/processing-py-site/releases

...as a zip attachment.

@jdf, you should be able to copy those to your server.

**Comment by jdf** [comment]
Already done it!

**Comment by jdf** [comment]
Thank you all.

**Comment by FeXd** [comment]
Thank you @jeremydouglass & @jdf!
