### ISSUE TITLE
Processing library issue VSCODE

### ISSUE THREAD

**Issue by marziabil** [jdf/Processing.py-Bugs#363]
I can't seem to import an external python library into my main processing file in VS Code. Here's the link to my code:  [https://github.com/marziabil/emojis/tree/main/emoji](url)

I was trying to import simpful in the file emoji.pyde; the simpful library is working fine by itself in the same folder. 

I am getting an error that the module can't be found when I try to run the emoji file.

**Comment by tabreturn** [comment]
You could download the simpful tar.gz from PyPi (https://pypi.org/project/simpful/#files), then extract the _simpful_ folder and place it in the root of your sketch directory so that you have something like --
```
emoji
├── emoji.pyde
├── simpful
│   ├── __init__.py
│   ├── fuzzy_aggregation.py
│   ├── ...
├── ...
```
This should solve your initial import issue -- **but** you'll run into another problem: the NumPy dependency. Processing.py [doesn't support Python libraries with C-extensions](https://py.processing.org/tutorials/python-jython-java/). The solution might be to:

- find an alternative to simpful that doesn't require NumPy;
- look at a Processing.py alternative without such limitations (like [py5](https://github.com/py5coding/py5)).

\* I must disclose that I'm involved in the py5 project

**Comment by marziabil** [comment]
Thank you for your response! I am currently trying to run the project with py5! :)
